### ISSUE TITLE
Gitlab Input: Can't use IRC Channel names with a dot in the name

### ISSUE THREAD

**Issue by fleaz** [fleaz/CptHook#30]
```
* 'groups[mag][0]' expected type 'string', got unconvertible type 'map[string]interface {}'
FATA[0000] Failed to unmarshal channelmapping into struct
``` 

Config:
```
gitlab:
        enabled: true
        default: "#mag.lab"
        groups:
            "mag.lab":
                - "#mag.lab"
            "fffd":
                - "#fffd"
```

The problem appears to be the "mag.lab" in line 5. Without the dot everything works as expected
